//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmer()
        {
            this.FarmerProducts = new HashSet<FarmerProduct>();
        }
    
        public string farmer_name { get; set; }
        public string farmer_surname { get; set; }
        public Nullable<System.DateTime> farmer_DOB { get; set; }
        public string farmer_cell { get; set; }
        public string farmer_email { get; set; }
        public string user_username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerProduct> FarmerProducts { get; set; }
        public virtual Login_Credentials Login_Credentials { get; set; }
    }
}
